pipeline {

    agent any

    stages {

        stage('Checkout Backend Source Code') {
            steps {
                git(
                    url: {git_url},
                    branch: {git_branch},
                    credentialsId: {git_credential}
                )
            }
        }

        stage('CI Test') {
            steps {
                echo 'CI pipeline is working'
            }
        }

    }

}